$aboutFile = Join-Path $PSScriptRoot "\about.md"
$aboutContent = Get-Content -Path $aboutFile -Raw
$developmentFile = Join-Path $PSScriptRoot "\development.md"
$developmentContent = Get-Content -Path $developmentFile -Raw

$generatedWarningMessage = "[//]: # (DO NOT EDIT: This file has been autogenerated, any changes will be overwritten)`r`n"
$combineSeparator = "`r`n`r`n***`r`n`r`n"
$combinedContent = $generatedWarningMessage + $aboutContent + $combineSeparator +
        $generatedWarningMessage + $developmentContent + $combineSeparator

$readmeFile = Join-Path $PSScriptRoot "\readme.md"
$combinedContent | Set-Content -Path $readmeFile

# Requires https://dotnet.microsoft.com/en-us/download
# And https://github.com/BUTR/Converter.MarkdownToBBCode
$readmeFileBbcodenm = Join-Path $PSScriptRoot "readme.bbcodenm"
& markdown_to_bbcodenm -i $readmeFile > $readmeFileBbcodenm